drop table PERSON if exists;

CREATE TABLE PERSON
(
  ID BIGINT IDENTITY PRIMARY KEY
, USERNAME VARCHAR2(50) NOT NULL
, FIRSTNAME VARCHAR2(50)
, LASTNAME VARCHAR2(50)
, PASSWORD VARCHAR2(50) NOT NULL
, HIRINGDATE DATE
, VERSION INT
, CREATED_AT VARCHAR2(50) NOT NULL
, MODIFIED_AT VARCHAR2(50) NOT NULL
, UNIQUE(USERNAME)
);